config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :orders
  resources :categories
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  resources :carts do
     member do
      get :add
      get :remove
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'welcome#home'
end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :item_orders
  has_many :items, through: :item_orders

  validates :quantity, presence: true
  validates :subtotal, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	before_action :set_cart

	def add
    if params[:item]
      @quantity = (params[:item][:quantity]).to_i
    else
      @quantity = 1
    end
    @item = Item.find(params[:id])
    @user = current_user
    user_cart = {@item.name => @quantity}

    if logged_in?
      chave = @user.username
    else
      chave = "not_logged"
    end

    if (!session[:current_cart].key? (chave))
      session[:current_cart][chave] = user_cart
    elsif (session[:current_cart][chave].key? (@item.name))
      session[:current_cart][chave][@item.name] += @quantity
    else
      session[:current_cart][chave].merge!(user_cart)
    end
    redirect_to items_path
	end

	def remove
    @item = Item.find(params[:id])
    @quantity = (params[:item][:quantity]).to_i
    @user = current_user

    if logged_in?
      chave = @user.username
    else
      chave = "not_logged"
    end

    if session[:current_cart].key? (chave)
      if session[:current_cart][chave][@item.name] > @quantity
        session[:current_cart][chave][@item.name] -= @quantity
      else
        session[:current_cart][chave].delete(@item.name)
        if session[:current_cart][chave].empty?
          session[:current_cart].delete(chave)
        end
      end
    end
    redirect_to items_path
  end

private
	def set_cart
		session[:current_cart] ||= {}
	end
end

app/views/carts/_empty.html.erb
<div class="container">
  <div class="jumbotron" style="background:#483D8B">
    <h1 align="center" >Carrinho Vazio
    <br><%= link_to "Comprar agora!", items_path , class: "btn btn-success btn-lg" %>
    </h1>
  </div>
</div>

app/views/carts/index.html.erb
<div class = "container">
<% if (!logged_in?) %>
  <% if session[:current_cart].key?("not_logged") %>
    <table class="table table-bordered">
      <tr>
        <th>Item</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
      <% session[:current_cart]["not_logged"].each do |item| %>
        <tr>
          <td>
            <%= link_to item[0], item_path(Item.find_by_name(item[0])) %>
          </td>
          <td>
            <%= item[1] %>
          </td>
          <td>
            $ <%= (Item.find_by_name(item[0])).price*item[1] %>
          </td>
        </tr>
      <% end %>
      <% else %>
        <%= render 'empty' %>
  <% end %>
<% else %>
  <% if session[:current_cart][current_user.username] %>
    <table class="table table-bordered">
      <tr>
        <th>Item</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
        <% session[:current_cart][current_user.username].each do |item| %>
          <tr>
            <td>
              <%= link_to item[0], item_path(Item.find_by_name(item[0])) %>
            </td>
            <td>
              <%= item[1] %>
            </td>
            <td>
              $ <%= (Item.find_by_name(item[0])).price*item[1] %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>Total</td>
          <td>
            <%= count_items_and_price[0] %>
          </td>
          <td>
            $ <%= count_items_and_price[1] %>
          </td>
        </tr>
      </table>
  <% else %>
    <%= render 'empty' %>
  <% end %>
<% end %>
<% if logged_in? && session[:current_cart][current_user.username] != nil  %>
  <%= form_for :order, url: orders_path do |f| %>
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
    <%= f.hidden_field :quantity, :value => count_items_and_price[0] %>
    <%= f.hidden_field :subtotal, :value => count_items_and_price[1] %>
    <% session[:current_cart][current_user.username].each do |item| %>
      <%= f.hidden_field :item_ids, multiple: true, :value => Item.find_by_name(item[0]).id %>
    <% end %>
    <h1 align = "center">
      <%= f.submit "Comprar", class: "btn btn-primary" %>
    </h1>
  <% end %>
<% end %>
<%= link_to 'Voltar', items_path %>
</div>