config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :orders
  resources :categories
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  resources :carts do
     member do
      get :add
      get :remove
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'welcome#home'
end

app/models/item.rb
class Item < ApplicationRecord

	has_many :item_categories
	has_many :categories, through: :item_categories

	has_many :item_orders
  has_many :orders, through: :item_orders

	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :item_categories, presence: true
	validates :price, numericality: { greater_than: 0 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :require_admin, only: [:new, :create, :update, :destroy]

  def index
    @items = Item.all
    @categories = []
		@categories_list = Category.all # para fazer o filtro
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
	  @item = Item.new
  end

  def edit
  	@item = Item.find(params[:id])
	end

  def create
  	@item = Item.new(item_params)

	  if @item.save
      redirect_to @item
  	else
    	render 'new'
  	end
  end

  def update
	  @item = Item.find(params[:id])

	  if @item.update(item_params)
	    redirect_to @item
	  else
	    render 'edit'
	  end
	end

	def destroy
    @item = Item.find(params[:id])

    session[:current_cart] = {}

    @item.destroy

    redirect_to items_path
  end

private
  def item_params
    params.require(:item).permit(:name, :description, :price, category_ids: [], order_ids: [])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1 align='center'>Editing item</h1>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>




<div class="signup-box">
  <div class="signup-box-content">
    <div class="row">
      <div class="col-xs-12">
        <%= form_for :item, url: item_path(@item), :html => {class: "form-horizontal", role: "form"}, method: :patch do |f| %>

          <% if @item.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@item.errors.count, "error") %> prohibited
                this item from being saved:
              </h2>
              <ul>
                <% @item.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :name %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :description %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.text_area :description, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :categories %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.select :categories, Category.pluck(:name), class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :price %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.number_field :price, class: "form-control", :min => '0', :step => "0.01" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1" align='center'>
            <%= f.submit class: "btn btn-primary btn-lg"%>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div align='center'>
  <%= link_to 'Back', items_path, class:"btn btn-primary" %>
</div>

app/views/items/index.html.erb
<div>
  <h1 align="center">Listando Todos os Itens</h1>
  <div class="btn-group" style = "left:80%" >
    <div class="form-group">
        <select name="filtro_categorias" class="ui fluid dropdown">
          <option>Selecione uma categoria</option>
          <option value="0">Todas as categorias</option>
          <% @categories_list.order("name").each do |categoryName| %>
            <option value="<%= categoryName.id %>">
              <%= categoryName.name %>
            </option>
          <% end %>
        </select>
    </div>
  </div>
</div>

<p align="center">
	<%= link_to 'Voltar', root_path , class: "btn btn-primary"%>
	<%= link_to 'New item', new_item_path, class: "btn btn-primary" %>
	<%= link_to 'Categorias', categories_path, class: "btn btn-primary" %>
  <%= link_to 'New category', new_category_path, class: "btn btn-primary"%>
  <%= link_to 'Carrinho', carts_path, class: "btn btn-success" %>
</p>

<br>
<div class="ui container">
  <div class="ui four cards">
    <% @items.order('name').each do |item| %>
    <div class="item-container">
      <img src="http://endlessfacts.com/upload/img/WB5Df14438473442.jpg">
      <div class="item-content">
        <div class="content">
          <div class="item-name">
            <%= item.name %>
          </div>
          <div class = "item-description">
            <%= item.description %>
          </div>
          <div class = "item-price">
            $ <%= item.price %>
          </div>
        </div>
        <div class="item-add-cart fa">
          <%= link_to add_cart_path(item),
                      class: 'ui bottom attached button',
                      id: ["add-item-#{item.id}"] do %>
            <%= fa_icon 'plus', quantity: 1 %>
            &nbsp;&nbsp;<%= "Add to cart" %>
          <% end %><br>
          <div align='center'>

            <%= form_for :item, url: add_cart_path(item), :method => :get  do |f| %>
              <%= f.number_field :quantity, :min => '0', :step => "1" %>
              <%= f.submit 'Adicionar ao carrinho', class: "btn btn-success"%>
            <% end %><br>
            <%= form_for :item, url: remove_cart_path(item), :method => :get  do |f| %>
              <%= f.number_field :quantity, :min => '0', :step => "1" %>
              <%= f.submit 'Remover do carrinho', class: "btn btn-default" %>
            <% end %><br>

            <%= link_to 'Edit', edit_item_path(item), class: "btn btn-warning" if isAdmin? %>
            <%= link_to 'Destroy', item_path(item),
                    method: :delete, class: "btn btn-danger",
                    data: { confirm: 'Are you sure?' } if isAdmin? %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<br>
<br>
<p align="center">
	<%= link_to 'Voltar', root_path , class: "btn btn-primary"%>
	<%= link_to 'New item', new_item_path, class: "btn btn-primary" %>
	<%= link_to 'Categorias', categories_path, class: "btn btn-primary" %>
  <%= link_to 'New category', new_category_path, class: "btn btn-primary"%>
  <%= link_to 'Carrinho', carts_path, class: "btn btn-success" %>
</p>

<span>Carrinho: </span> <%= session[:current_cart] %>

app/views/items/new.html.erb
<h1 align = 'center'>New Item</h1>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<%= render 'shared/errors', obj: @item %>

<div class="signup-box">
  <div class="signup-box-content">
    <div class="row">
      <div class="col-xs-12">
        <%= form_for :item, :html => {class: "form-horizontal", role: "form"},  url: items_path do |f| %>
        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :name %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :description %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.text_area :description, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :categories %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :price %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.number_field :price, class: "form-control", :min => '0', :step => "0.01" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1" align='center'>
            <%= f.submit class: "btn btn-primary btn-lg"%>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<br>
<br>
<div align='center'>
  <%= link_to 'Back', items_path, class: "btn btn-primary" %>
  <%= link_to 'Categorias', categories_path, class: "btn btn-primary" %>
  <%= link_to 'Items list', items_path, class: "btn btn-primary" %>
</div>

app/views/items/show.html.erb
<div class="ui container" align = 'center'>
  <table class="table table-striped">
    <tr>
      <td>
        <strong>Name:</strong>
      </td>
      <td>
        <%= @item.name %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Description:</strong>
      </td>
      <td>
        <%= @item.description %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Categories:</strong>
      </td>
      <td>
        <%= @item.category_ids %>
      </td>
    </tr>

    <tr>
      <td>
        <strong>Price:</strong>
      </td>
      <td>
        <%= @item.price %>
      </td>
    </tr>
  </table>

</div>


<% if @item.categories.any? %>

   <p>Categories: </p>

<% end %>

<p>
  <strong>Category:</strong>

</p>

<div align = 'center'>

  <%= link_to 'Back', categories_path, class: "btn btn-primary"%>
  <%= link_to 'New Item', new_item_path, class:"btn btn-primary" %>

</div>