config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :orders
  resources :categories
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  resources :carts do
     member do
      get :add
      get :remove
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'welcome#home'
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :item_categories
  has_many :items, through: :item_categories

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, only: [:new, :create]

  def index
    @categories = Category.all
    @items = []
  end

  def show
    @category = Category.find(params[:id])
    @items = []
  end

  def new
		@category = Category.new
  end

  def create
  	@category = Category.new(category_params)

		if @category.save
    	redirect_to @category
  	else
    	render 'new'
  	end
  end

  private
  def category_params
    params.require(:category).permit(:name, item_ids: [])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1 align = "center">Listing categories</h1>

<div class="ui container-fluid" align='center'>

  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Items</th>
    </tr>

    <% @categories.order('name').each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category), class:"btn btn-success" %></td>
        <td>
        	<% category.item_ids.each do |item_id| %>
            <% @items << Item.find(item_id).name %>
          <% end %>

          <% @items = @items.sort %>

          <% @items.each do |itemName| %>
            <span class = "label label-info"><%= link_to itemName, item_path(Item.find_by_name(itemName)) %></span>
          <% end %>

          <% @items.clear %>
        </td>
    <% end %>
  </table>
  <br>

</div>
<div align = "center">
  <%= link_to 'Voltar', root_path, class: "btn btn-primary" %> <%= link_to 'New category', new_category_path, class: "btn btn-primary" if isAdmin? %>
</div>

app/views/categories/new.html.erb
<h1 align = 'center'>New Category</h1>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<div class="signup-box">
  <div class="signup-box-content">
    <div class="row">
      <div class="col-xs-12">
        <%= form_for :category, :html => {class: "form-horizontal", role: "form"}, url: categories_path do |f| %>

        <% if @category.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@category.errors.count, "error") %> prohibited
              this category from being saved:
            </h2>
            <ul>
              <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.label :name %><br>
          </div>
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-1" align='center'>
            <%= f.submit class: "btn btn-primary btn-lg"%>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div align='center'>
    <%= link_to 'Back', categories_path, class: "btn btn-primary" %>
</div>

app/views/categories/show.html.erb
<div>
	<h1 align="center">Filtrando por <%= @category.name %></h1>
	<div class="btn-group" style = "left:80%" >
		<div class="form-group">
				<select name="filtro_categorias" class="ui fluid dropdown">
					<option>Selecione uma categoria</option>
          <option value="0">Todas as categorias</option>
					<% Category.all.order("name").each do |categoryName| %>
						<option value="<%= categoryName.id %>">
							<%= categoryName.name %>
						</option>
					<% end %>
				</select>
		</div>
	</div>
</div>

<br>
<div class="ui container">
	<div class="ui four cards">
		<% @category.item_ids.each do |item_id| %>
			<% @items << Item.find(item_id).name %>
		<% end %>
		<% @items = @items.sort %>

		<% @items.each do |item_name| %>
			<% item = Item.find_by_name(item_name)%>

			<div class="item-container">
				<img src="http://endlessfacts.com/upload/img/WB5Df14438473442.jpg">
				<div class="item-content">
					<div class="content">
						<div class="item-name">
							<%= item.name %>
						</div>
						<div class = "item-description">
							<%= item.description %>
						</div>
						<div class = "item-price">
							$ <%= item.price %>
						</div>
					</div>
					<div class="item-add-cart fa">
						<%= link_to add_cart_path(item),
												class: 'ui bottom attached button',
												id: ["add-item-#{item.id}"] do %>
							<%= fa_icon 'plus' %>
							&nbsp;&nbsp;<%= "Add to cart" %>
						<% end %><br>

						<div align='center'>

							<%= form_for :item, url: add_cart_path(item), :method => :get  do |f| %>
								<%= f.number_field :quantity, :min => '0', :step => "1" %>
								<%= f.submit 'Adicionar ao carrinho', class: "btn btn-success"%>
							<% end %><br>
							<%= form_for :item, url: remove_cart_path(item), :method => :get  do |f| %>
								<%= f.number_field :quantity, :min => '0', :step => "1" %>
								<%= f.submit 'Remover do carrinho', class: "btn btn-default" %>
							<% end %><br>

							<%= link_to 'Edit', edit_item_path(item), class: "btn btn-warning" if isAdmin? %>
							<%= link_to 'Destroy', item_path(item),
											method: :delete, class: "btn btn-danger",
											data: { confirm: 'Are you sure?' } if isAdmin? %>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

<p align="center">
	<%= link_to 'Voltar', root_path , class: "btn btn-primary"%>
	<%= link_to 'New item', new_item_path, class: "btn btn-primary" %>
	<%= link_to 'Categorias', categories_path, class: "btn btn-primary" %>
</p>

<span>Carrinho: </span> <%= session[:current_cart] %>