config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :orders
  resources :categories
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  resources :carts do
     member do
      get :add
      get :remove
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'welcome#home'
end

app/views/layouts/_messages.html.erb
<div class="row">
   <div class="col-xs-10 col-xs-offset-1">

      <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
         <a href="#" class="close" data-dismiss="alert">×</a>
         <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
      <% end %>

   </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
   <div class="container-fluid">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <%= link_to "Dinner Dash 2", root_path, class: "navbar-brand", id: "logo" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav navbar-nav navbar-right">
            <% if logged_in?  %>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
              <li class="dropdown">
                <% user = current_user %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= user.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to carts_path, class: 'item dd cart-link' do %>
                      <span align = "left">Carrinho</span>
                      <div class="ui label" id="cart-item-count">
                        <%= count_items_and_price[0] %>
                      </div>
                      <% end %>
                  </li>
                  <li>
                    <%= link_to "Comprar", items_path %>
                  </li>
                  <li>
                    <%= link_to "Perfil", user_path(user) %>
                  </li>
                  <li>
                    <%= link_to "Editar sua conta", edit_user_path(user) %>
                  </li>
                  <li>
                    <%= link_to "Seus pedidos", orders_path %>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                </ul>
              </li>
            <% else %>
            <li>
              <%= link_to login_path ,class: 'item dd cart-link' do %>
                <%= fa_icon('user') %>
                <span>&nbsp;Login&nbsp;</span>
              <% end %>
            </li>
            <li>
              <%= link_to signup_path ,class: 'item dd cart-link' do %>
                <%= fa_icon('user') %>
                <span>&nbsp;Signup&nbsp;</span>
              <% end %>
            </li>
            <% end %>
            <li>
              <%= link_to carts_path, class: 'item dd cart-link' do %>
                <%= fa_icon('shopping-cart') %>
                <span>&nbsp;Cart&nbsp;</span>
                <div class="ui label" id="cart-item-count">
                  <%= count_items_and_price[0] %>
                </div>
              <% end %>
            </li>
         </ul>
      </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerDash</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/messages' %>
  <%= render 'layouts/navigation' %>
  <body>
    <%= yield %>
  </body>
</html>